ALTER TABLE baguni_db.link
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE baguni_db.link
SET created_at = '2024-01-01 00:00:00',
    updated_at = '2024-01-01 00:00:00';


