ALTER TABLE baguni_db.user
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    MODIFY COLUMN role ENUM ('ROLE_ADMIN', 'ROLE_USER', 'ROLE_TEST') not null;
