name: Baguni Staging Batch-Module CI/CD

on:
  push:
    branches:
      - 'staging' # 배포 대상 브랜치
    paths:
      - 'baguni-common/**'
      - 'baguni-infra/**'
      - 'baguni-batch/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      docker-hub-username: 'minkyeu' # 김민규
      docker-hub-repo: 'baguni'
      docker-hub-password: ${{ secrets.DOCKERHUB_PASSWORD_STAGING }}
      module-name: 'baguni-batch'
      project-directory: '/home/project/baguni/staging' # path to docker-compose.yaml

    steps:
      # 저장소 Checkout
      - name: Checkout source code
        uses: actions/checkout@v4

      # Gradle 실행 권한 부여
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # JDK 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      # Spring boot application, Docker image 빌드
      - name: Build and Deploy ${{ env.module-name }} Module
        run: |
          ./gradlew -p ${{ env.module-name }} clean build -x test
          docker build -t ${{ env.docker-hub-username }}/${{ env.docker-hub-repo }}:${{ env.module-name }} ${{ env.module-name }}

      - # Docker hub 로그인
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.docker-hub-username }}
          password: ${{ env.docker-hub-password }}
      - # Docker hub 업로드
        name: Publish to docker hub
        run: docker push ${{ env.docker-hub-username }}/${{ env.docker-hub-repo }}:${{ env.module-name }}

      - name: Deploy on Test-Server
        uses: appleboy/ssh-action@master
        with:
          host: minlife.me
          port: 4242
          username: root
          password: ${{ secrets.SSH_TEST_SERVER_KYEU_PASSWORD }}
          script: |
            echo "login docker hub for private repository access ..."
            echo ${{ env.docker-hub-password }} | docker login -u ${{ env.docker-hub-username }} --password-stdin
            
            echo "docker - pulling..."
            docker pull ${{ env.docker-hub-username }}/${{ env.docker-hub-repo }}:${{ env.module-name }}
            
            echo "moving to project directory..."
            cd ${{ env.project-directory }}
            
            echo "restarting container..."
            docker compose down ${{ env.module-name }}
            docker compose up ${{ env.module-name }} -d
